## labels to be added to the config maps
labels:
  ## grafana_dashboard Enables dashboard import via Grafana sidecar
  ## ref: https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards
  grafana_dashboard: "1"
dashboardsFolder: my-team-dashboards #< the desired dashboards folder >
importFromValue:
  # dashboardName: |-
  #   {
  #     dashboard json
  #   }
